---
- name: Instance creation
  hosts: localhost
  connection: local
  gather_facts: false
  become: true
  vars_files:
    - vars/global.yml
    - vars/vpc.yml
    - vars/instance.yml

  environment:
    AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
    AWS_SESSION_TOKEN: "{{ lookup('env', 'AWS_SESSION_TOKEN') }}"

  vars:
    subnet_id: "{{ hostvars['virtual_host']['subnet_id'] }}"
    public_key: "{{ lookup('env', 'PRIVATE_KEY') }}.pub"

  tasks:
    - name: EC2 public key register
      amazon.aws.ec2_key:
        name: '{{ access_key }}'
        region: '{{ aws_region }}'
        key_material: "{{lookup('file', '{{ public_key }}') }}"
        force: yes

    - name: EC2 provisioning
      community.aws.ec2_instance:
        region: '{{ aws_region }}'
        vpc_subnet_id: '{{ subnet_id }}'
        name: '{{ instance_name }}'
        key_name: '{{ access_key }}'
        security_group: '{{ security_group_name }}'
        instance_type: '{{ instance_type }}'
        image_id: '{{ image_id }}'
        network:
          assign_public_ip: true
        tags:
          system: '{{ project_name }}'
          environment: 'production'
        wait: true
        state: running
        user_data: "{{lookup('file', '{{ user_data_file }}') }}"
        instance_role: '{{ iam_role }}'
      register: ec2_result
