name: Ansible basic
on: 
  workflow_dispatch:
jobs:
  ansible-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - run: ansible --version
